### ISSUE TITLE
Friendly suggestion: add code quality checks

### ISSUE THREAD

**Issue by freekmurze** [Marbles/statamic-sitemap#2]
Hi Rias,

great to see you contributing such nice stuff.

Currently there are no automatic quality checks running. Adding such services demonstrates to potential users that the package was coded up with quality in mind.

Personally I'm big fan of these services:

- [Insights](https://insight.sensiolabs.com/)
- [Scrutinizer](https://scrutinizer-ci.com/)
- [StyleCi](https://styleci.io/) (codestyle)
- [Travis](https://travis-ci.org) (testing)

All of these services are free and have badges that can added to the readme. 

Of course using those services is by no means required, but aside from the confidence building for users, they've caught many stupid mistakes that I made in my code. Hope these services could be of some use for you as well.

**Comment by riasvdv** [comment]
Yeah that's on the roadmap :) sadly there doesn't seem to be a good way to automatically test Statamic Addons, but the code style stuff is something I'll definitely look into.

If an Addon gets too big I'll probably try to split the code to a seperate package and write tests for that.

Thanks for the suggestions!
